### ISSUE TITLE
False positive cyclic dependencies in header files

### ISSUE THREAD

**Issue by jens-auer** [wenns/sonar-cxx#559] opened 2015-07-07 08:39 UTC
Hi,

sonar-cxx complains about cyclic dependencies in two of my header files. From visual inspection, I am pretty sure that this a false positive especially because one of the files only includes two system headers. Sonar-cxx thinks that there is a cycle A-B, but B is the mentioned file.

I am not able to give out the source code of my file, but I my be able to give logging or debugging output. Is there anything I could do?

Best wishes,
  Jens

**Comment by guwirth** [comment] 2015-07-10 18:39
For the dependency check only the includes are needed. Could you provide a simple example with the same include structure (files can be empty except the includes).

**Comment by jens-auer** [comment] 2015-07-14 20:39
Hi Günther,

 

I’ve tried to assemble a small set of files which reproduces the issue, but this only worked inside the same project structure as the two files showing the issue. The files are attached, but as soon as I put them into a different module in the project, it does not show the cyclic dependencies anymore.

 

I suspect that the problem has something to do with the way I use the include files and with SonarQube’s definition of dependencies. In the project, I basically have a structure like this:

module/Include/module/a.h: this includes module/Include/module/sub1/b.h

module/Include/module/module_fwd.h

… more headers in this directory …, some referencing headers in sub1

module/Include/module/sub1/b.h

module/Include/module/sub1/c.h: this includes module_fwd.h

 

My guess is that sub1 is counted as a different component, and this leads to the cyclic dependencies. I would like to provide more input, but I don’t what would help.

 

Best wishes,

  Jens

 

Von: Günter Wirth [mailto:notifications@github.com] 
Gesendet: Freitag, 10. Juli 2015 20:39
An: wenns/sonar-cxx
Cc: Jens Auer
Betreff: Re: [sonar-cxx] False positive cyclic dependencies in header files (#559)

 

For the dependency check only the includes are needed. Could you provide a simple example with the same include structure (files can be empty except the includes).

**Comment by guwirth** [comment] 2015-07-14 21:12
As far as I understand each directory is a component and an include from another directory is a dependency. I think @Typz wrote the code and could help?

**Comment by jens-auer** [comment] 2015-07-14 21:38
I think that collides with one of my usual patterns. Every folder has a _fwd.h header with forward declarations, but I sometimes also include the one in subdirectories, e.g.

libA/include/libA/libA_fwd.h

libA/include/libA/sub1/sub1_fwd.h

 

In this case, libA_fwd.h also includes sub1_fwd.h to create one header with all forward declarations. In sub1, headers prefer to use forward declarations and thus include libA_fwd.h if needed. This immediately forms a cyclic dependency in these terms.

 

I don’t think it is safe to assume that a directory equals a component. I can think of using directories to e.g. structure a component’s interfaces. Consider a class implementing a modem with two interfaces connection management and data handling. I can imagine a structure like

modem/Modem.h

modem/connection/Address.h

modem/connection/Connection.h

modem/connection/Dialer.h

modem/data/Data.h

modem/data/SomeTypeForData.h

 

In this case, the interfaces of a component are logically structured into two groups, but they do not form new components. An automated mapping between directories and components (or packages) seems very Java-like, but I don’t know if you can assume that for C++ in general. 

 

Best wishes,

  Jens

Von: Günter Wirth [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. Juli 2015 23:12
An: wenns/sonar-cxx
Cc: Jens Auer
Betreff: Re: [sonar-cxx] False positive cyclic dependencies in header files (#559)

 

As far as I understand each directory is a component and an include from another directory is a dependency. I think @Typz <https://github.com/Typz>  wrote the code and could help?

**Comment by guwirth** [comment] 2015-07-14 22:15
@jens-auer If you like to provide a generic solution there are not so many choices in C++:
* use the directories
* use namespaces
* manually define which includes are internal and which are external for the component. 

But do you have any concrete ideas how to improve this?

**Comment by jens-auer** [comment] 2015-07-20 07:53
Hi Guenther,

the problem is I don't have a better idea on how to do. Without language-level support for something like packages or component, I don't think there is a general way to implement a checker without heavy configuration from the user like you proposed in the third alternative.

Thinking about, maybe the rule could be relaxed to not consider sub-directories as individual components w.r.t to their parent directory? This came to my mind when I looked at the boost range library:
boost/
boost/range
boost/range/algorithm
boost/range/adaptor

Here, have a boost/range/algorithm.hpp which includes all headers in boost/range/algorithm, and multiple includes from boost/range/algorithm/*.h to boost/range headers. With the current scheme, these would all count as cyclic dependencies.

What if the definition would be changed to only consider directories which are not a parent of the current directory? This would skip dependencies from boost, boost/range into boost/algorithm, but still consider dependencies between e.g. boost/range/algorithm and boost/range/adapter as cyclic if there mutual includes. 

PS: C++ really needs modules... Let's hope the proposal makes it into the next standard.

**Comment by guwirth** [comment] 2015-07-22 05:11
@jens-auer Code for this is here https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/squid/DependencyAnalyzer.java. May be you can have a closer look?

**Comment by Typz** [comment] 2015-07-22 07:03
Not sure that would help: in recent sonar versions, dependency metrics are computed directly by the platform...

So the only "tweak" that can be done is to ignore some file dependency. Maybe that could be done by having a list of includes that do not count for dependencies, or having a pragma in those files...

But in any case, I am not so sure this is really a "bug" of the plugin; the tool reports dependencies between files/folders, and that should be as precise as possible. Interpreting these, to decide which dependencies are correct and which are problematic is the developers job: you can always mark one issue as 'ignore' if it is the expected behavior, whatever the reason.

-- 
Francois

**Comment by jens-auer** [comment] 2015-07-22 09:05
@Typz Does this mean that SonarQube computes the dependency metrics for C++ code? How does it do this without understanding the programming language?

I am also unsure if my proposed fix is a good idea or not, and also if this a bug. The rule has a precise definition (which I didn't know when I opened the issue), and reports violations. The problem is that it makes some assumptions which are not generally true, at least for C++ code where there is no mapping between directories and components. Of course, we structure our code base in a reasonable way, but this has no meaning to the language.

On the other hand, I am not sure if the directory == component heuristic is actually correct. My components are usually hierarchical, so if I have something like
C1
C1/A
C1/A/B
C1/C
C2
, this forms a component C1 with sub-components A and C. A has a sub-component B. The question than is how to treat includes from A into sub-components B and vice a versa.

I think that in the end the developer has to somehow communicate what a component is. One definite source could be the SonarQube modules definition, but this is only good for top-level components. Manually defining exceptions in SonarQube seems reasonable because I don't want to put special pragmas or comments in the code just for SonarQube.

**Comment by Typz** [comment] 2015-07-22 13:43
In latest sonarqube versions, the computations of metrics/cycles/deps Matrix are moved to core. This is done based on the dependency graph (e.g. Which file/component depends on which other files/component), which is provided by each language plugin.

The component in this sense is what appears when you drill into your project: e.g. folder with c++ project.

Since there is no other notion in c++, the only thing we can use is the folder to approximate component/sub-component... And the dependency part just shows issues with the "structure" that is provided to sonar.

In your example, there should no problem reported as long as folders as "self contained": e.g. files from A can use files from A/B, but not the opposite...

-- 
Francois

**Comment by jens-auer** [comment] 2015-07-22 16:56
I think I can live with the heuristic and flag the two files in SonarQube itself. I like this more than implementing some other complicated approximation which would create more confusion.

**Comment by guwirth** [comment] 2015-07-22 18:54
@jens-auer Other possibility is to use the XPath or RegEx checks to create own warnings: https://github.com/wenns/sonar-cxx/wiki/Create-Custom-Rules

Here you can define a folder name and search for a string in a include. Maybe that helps?

**Comment by jens-auer** [comment] 2015-09-14 13:03
I have given this some more thoughts, and I think the conclusion is that the modules and dependencies need to be defined by the developer. I think that there already is a place for that: the build system. I would propose to write plugins for the common build systems to define the modules, and then use this information for checking.

**Comment by guwirth** [comment] 2015-10-10 16:15
I'm closing this issue. Please re-open if still a problem.

**Closed by guwirth** 2015-10-10 16:15 UTC
Labels: docu request, question
