### ISSUE TITLE
V0.9.2 release: remaining issues?

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#363] opened 2015-01-05 08:35 UTC
Hello all, which points are remaining to finish the V0.9.2 release?

**Created some filters to track V0.9.2 changes:**
* [Docu request](https://github.com/wenns/sonar-cxx/issues?q=+label%3A%22docu+request%22+)
* [Merged](https://github.com/wenns/sonar-cxx/issues?q=merged%3A%3E2014-06-17)
* [Closed issues](https://github.com/wenns/sonar-cxx/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E2014-06-17)
 * [Bugs](https://github.com/wenns/sonar-cxx/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E2014-06-17+label%3Abug)
 * [Enhancements](https://github.com/wenns/sonar-cxx/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E2014-06-17+label%3Aenhancement)

**Comment by wenns** [comment] 2015-01-05 10:33
Besides polishing of already merged stuff (C compatibility etc.) I think it is fair to merge the reactor / multi module thing: its is already sitting very long in the queue and is requested by both Jorge and Bert. But thats the last feature I want to merge in the 0.9.2-cycle. Time to test in production, gentlemen. 

BTW: I've drafted the release procedure: https://github.com/wenns/sonar-cxx/wiki/Release-Procedure.

**Comment by guwirth** [comment] 2015-01-05 11:36
Tried to assign all issues to a milestone (0.9.2 or 0.9.3). Please correct if I did it wrong.

**Comment by guwirth** [comment] 2015-01-05 12:55
@wenns Not possible to set assignee **lcintrat** and **Zetten**. Maybe you have to configure this for the repository.

**Comment by wenns** [comment] 2015-01-05 13:34
Should work now

**Comment by guwirth** [comment] 2015-01-05 18:58
POM is ready, contains all developers.

**Comment by guwirth** [comment] 2015-01-05 19:00
All issues and pull requests are assigned to developers and milestones.

**Comment by guwirth** [comment] 2015-01-05 19:02
@wenns will create this as draft in this issue or do you have it already?
* compose a list of fixed bugs
* compose a list of enhancements
* don't forget to thank to the contributors

**Comment by jmecosta** [comment] 2015-01-06 11:30
started running in production code... so far no regressions..

**Comment by guwirth** [comment] 2015-01-06 19:16
Below a first draft for 0.9.2 enhancements. Still not complete at least xunit and multi-module missing. **Please verify.** Will provide another list with bugfixes.

# enhancements

* **preprocessor enhancements:**
 * improve rescan and parameter extraction of cascaded macros (#302, #304)
 * support expressions in includes (#227, #312)
 * support named variadic arguments (#300, #301)
 * support uin64 values (#224, #308)
* **parser enhancements:**
 * improve parsing speed (#299, #294, #260)
 * ignore C++ keywords in C files (sonar.cxx.cFilesPatterns) (#291, #345, #353)
 * support special meaning of token paste operator for GCC (#214, #298)
 * support Visual Studio inline assembler (#262, #333, #340)
 * support GCC case range extension (#235)
 * support ISO C99 compound literals (#237)
 * support ISO C99 designated initializers (#236)
* **metrics enhancements:**
 * compute file and package dependencies (based on #include) ( #232, #292)
 * add metrics to count documented and undocumented APIs (#307, #318, #338)
 * add metric to count number of violations of each type (#177)
* **rule enhancements:**
 * new rules to check for violations on cyclic package dependencies (#232, #292)
 * new rule to check for undocumented API (#307, #318, #338)
 * new rule FileRegularExpressionCheck: can be used to create rules which will be triggered when a file matches a given regular expression (#339, #179)
 * new rule LineRegularExpressionCheck: can be used to create rules which will be triggered when a line matches a given regular expression (#341, #179)
 * new rule FileEncodingCheck: check if all characters of a file can be encoded with the predefined charset (#223, #328)
 * new rule MissingIncludeFileCheck: generate a violation for missing include files (#52, #239)
 * new rule SwitchLastCaseIsDefaultCheck: test that a switch statement has 'default' label and that the 'default' is the final case (#320)
 * XPathCheck, FileRegularExpressionCheck , LineRegularExpressionCheck: new option allows Ant-style patterns to match a path (#335)
 * UselessParenthesesCheck: ignores generic code now  (#231)
 * TooManyStatementsPerLineCheck: new option to allow case and break in one line (#230)
 * TooLongLineCheck: add a tab width setting to compute the length of the line more accurate (#233)
 * MagicNumberCheck: improve magic number detection - const variables are no more violations (#296, #332) 
 * Unsupported Code Checker Custom Rules: make import of invalid XML rule files more stable (#254)
 * update Cppcheck messages for 1.67 release (#286, #264)
 * update PC-lint messages for 9.00l release candidate (#264)
* **coverage enhancements:**
 * possibility to set coverage for source files without coverage report to zero to get more realistic Technical Debt values (sonar.cxx.coverage.forceZeroCoverage) (#218, #321)
 * Bullseye coverage reports: support coverage data on top level (src tag without folder tag) (#243, #250, #251)
 * Bullseye coverage reports: make path handling more robust (#273, #277)
* add SQALE model definitions for the built-in checks (#199)

**Comment by guwirth** [comment] 2015-01-06 19:36
# bugfixes
* Preprocessor does not support uint64 (#224)
* No meaningful error message if force-included file cannot be found (#225)
* Preprocessor does not support preprocessor expressions in includes (#227)
* Bulleye coverage file is not parsed correctly (#243)
* Server crash after updating 'External rules definition' with 0.9.1 (#253)
* How can I find out whats going on (#260)
* Unit test results not displayed in widget (#263)
* Bullseye based coverage import reports 'cannot find the file ...' (#273)
* Issues in digesting boost test results (#276)
* Very slow performance of nested parenthesis (#294)
* Const declarations are detected as magic numbers when not inside a function (#296)
* Unable to parse named variadic arguments (#300)
* Incomplete macro replacement rescanning (#302)
* NPE in org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitMemberDeclarator (#327)
* Cannot feed Valgrind report (#336)

**Comment by jmecosta** [comment] 2015-01-06 19:44
Looks very good

**Comment by guwirth** [comment] 2015-01-06 19:47
# Thanks ....

go to all contributors (in alphabetical order):

@Bertk
@guwirth
@jmecosta
@lcintrat
@Typz
@Zetten

... and all people which were active on the Issue Tracker!

**Comment by wenns** [comment] 2015-01-06 20:02
Superb ;)

**Comment by wenns** [comment] 2015-01-07 11:11
Have extended the integration test documentation by an use case mind map. 
https://github.com/wenns/sonar-cxx/wiki/Integration-test-suite
Helps to reason about things like the roadmap.

**Comment by wenns** [comment] 2015-01-07 14:24
The checks from the repos c++ SonarQube and c++ SonarQube Common.

**Comment by wenns** [comment] 2015-01-07 14:54
I think I spotted a performance regression:

```
Sensor CxxRatsSensor...
15:50:08.432 INFO  - Sensor CxxRatsSensor done: 1174 ms
15:50:08.432 INFO  - Sensor CxxXunitSensor...
15:50:09.503 INFO  - Sensor CxxXunitSensor done: 1071 ms
15:50:09.504 INFO  - Sensor CxxCoverageSensor...
15:50:13.196 INFO  - Sensor CxxCoverageSensor done: 3692 ms
15:50:13.197 INFO  - Sensor CxxCppCheckSensor...
15:50:14.322 INFO  - Sensor CxxCppCheckSensor done: 1125 ms
15:50:14.323 INFO  - Sensor CxxVeraxxSensor...
15:50:15.140 INFO  - Sensor CxxVeraxxSensor done: 817 ms
15:50:15.140 INFO  - Sensor CxxValgrindSensor...
15:50:15.950 INFO  - Sensor CxxValgrindSensor done: 810 ms
```

I had no reports configured: the sensors spent each 1 s. doing basically nothing. Pretty sure it wasnt like that before.

**Comment by jmecosta** [comment] 2015-01-07 14:57
I can check this to.

**Comment by wenns** [comment] 2015-01-08 13:00
Happens on big projects, was due to the replacement of the Ant-based implementation with something other. Will just revert this commit. Ant, welcome back.

**Comment by jmecosta** [comment] 2015-01-08 14:03
interesting... i have good results
20:51:53.977 INFO  - Sensor CxxXunitSensor done: 44 ms
20:51:53.977 INFO  - Sensor CxxCoverageSensor...
20:51:53.996 INFO  - Sensor CxxCoverageSensor done: 19 ms
20:51:53.996 INFO  - Sensor CxxCppCheckSensor...
20:51:54.003 INFO  - Sensor CxxCppCheckSensor done: 7 ms
20:51:54.003 INFO  - Sensor CxxVeraxxSensor...
20:51:54.011 INFO  - Sensor CxxVeraxxSensor done: 8 ms
20:51:54.011 INFO  - Sensor CxxValgrindSensor...
20:51:54.018 INFO  - Sensor CxxValgrindSensor done: 7 ms

C:\Tekla\BuildTools\sonar-runner
SonarQube Runner 2.3
Java 1.7.0_71 Oracle Corporation (64-bit)
Windows 8.1 6.3 amd64

**Comment by wenns** [comment] 2015-01-13 23:33
The performance hit was really obvious. It can be clearly seen in the code. The implementation has tried *every single path* under the basedir against the pattern. This is just not very smart. Should have noticed it earlier.

**Comment by wenns** [comment] 2015-01-14 00:51
Guys, what did your testing say? Do I have an OK for releasing the current HEAD?

**Comment by jmecosta** [comment] 2015-01-14 06:12
I think so

**Comment by guwirth** [comment] 2015-01-14 08:56
* for boost unit test only simple mode can be used currently, but for me it is ok to support this with V0.9.3
* final test with version from yesterday open from my side (doing it today)

**Comment by wenns** [comment] 2015-01-14 13:21
Ok. I'll wait for another day or two. My own test in production can be considered as successful. Found one preprocessor issue (fixed) and one minor grammar issue (deferred).

**Comment by Zetten** [comment] 2015-01-14 14:18
The current HEAD (770abf8) looks good on my projects too - no unexpected changes in violations or metrics. Analysis seems very slightly quicker as well, but it could just be noise.

Due to my mixed-language modules I have to comment out the DependencyAnalyzer use in CxxSquidSensor, but everything else seems fine.

**Comment by guwirth** [comment] 2015-01-14 18:45
Did a test with SQ 4.5.2 (test database), sonar-runner 2.4, cxx 0.9.2 on Windows 7 x64
* we ignore parsing errors and are not using any AST based functions yet
* **used functionality is ok => release**

Settings:
```INI
# required metadata
sonar.projectKey=xxx
sonar.projectName=yyy
sonar.projectVersion=1.2.3

# no test of multi-language or multi-module
sonar.language=c++

# path to source directories
sonar.sources=.
sonar.cxx.includeDirectories=.

# special cxx settings
sonar.cxx.errorRecoveryEnabled=true
sonar.cxx.coverage.forceZeroCoverage=true
sonar.cxx.xunit.provideDetails=false
sonar.cxx.forceIncludes=VS10Macros.h

sonar.cxx.suffixes.sources=.c,.cpp
sonar.cxx.suffixes.headers=.h,.hh,.hpp,.inl
sonar.exclusions=**/_*.*,**/*_i.*,**/*_p.*,**/*Test*/**,**/*Example*/**,**/*Demo*/**,**/resource.h,**/*_obsolete/**,**/*_deprecated/**

# paths to the reports
sonar.cxx.cppcheck.reportPath=reports/cppcheck.xml
sonar.cxx.other.reportPath=reports/cxx-*.xml
sonar.cxx.coverage.reportPath=reports/coverage-*.xml
sonar.cxx.xunit.xsltURL=boosttest-1.x-to-junit-1.0.xsl
sonar.cxx.xunit.reportPath=reports/*.test.boostd.exe.log.xml
```

**Comment by Bertk** [comment] 2015-01-14 19:03
I guess there is an issue with XPathCheck (cxx.checks) and visitFile method. I get results only if the matchFilePattern is empty. I use ```xpathQuery = //IDENTIFIER[@tokenValue='OutputDebugString']```
and when I use ```matchFilePattern= **/*.cpp``` nothing is detected. It works without the matchFilePattern. The file pattern support should be removed. 
I used SQ 4.5.2, Windows 7 64bit, JDK 1.7.u71, sonar-runner 2.4
Beside this issue - everything looks OK.

**Comment by guwirth** [comment] 2015-01-14 20:05
See description: /**/*.cpp - matches all .cpp files in all directories (you have to define the root directory '/')

**Comment by wenns** [comment] 2015-01-14 20:45
Guys, its done: https://github.com/wenns/sonar-cxx/releases/tag/cxx-0.9.2
Finally.
Thanks *A LOT* to all of you. 
It was a quite busy chrismas offtime...

**Closed by wenns** 2015-01-14 20:45 UTC
Labels: question, waiting for answer

**Comment by jmecosta** [comment] 2015-01-15 06:21
Thanks everyone also for the new release :)

**Comment by wenns** [comment] 2015-01-15 08:33
Almost forgotten: There is one last point in the release procedure checklist: "Tweet/Announce". Can you guys do that on your channels?

**Comment by jmecosta** [comment] 2015-01-15 09:51
done, twitter and google+
