### ISSUE TITLE
More then 50 includeDirectories leads to 'Error evaluating expression ..' error messages

### ISSUE THREAD

**Issue by KevinArturia** [wenns/sonar-cxx#545] opened 2015-07-03 14:20 UTC
I have a project which has lots of includes path.

As soon as I have more than 50 path in the sonar.cxx.includeDirectories, I get tons of error message like the following in my log:

    Error evaluating expression '' for AstExp 'IDENTIFIER: __has_include_next', assuming 0

**Comment by jmecosta** [comment] 2015-07-03 14:23
Can you check that all include paths are pass to the analysis they can be
found at start. If they are not then its your include definition that
contains everything invalid chars between include

**Comment by KevinArturia** [comment] 2015-07-03 14:33
Thanks for the fast reply.
I am sure that all the paths are corrects and can be accessed from the analysis workspace.

**Comment by guwirth** [comment] 2015-07-03 15:11
Think @jmecosta is speaking about the log file. At the beginning there is a section with includes paths.

Error is from: https://github.com/wenns/sonar-cxx/blob/2b51517642574b89554d3efc5c60ac8b8e0fe9a2/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/ExpressionEvaluator.java :: evalToInt. __has_include_next can't be converted to an integer value.

__has_include_next is a Clang language extension: http://clang.llvm.org/docs/LanguageExtensions.html

***Include File Checking Macros***
Not all developments systems have the same include files. The __has_include and __has_include_next macros allow you to check for the existence of an include file before doing a possibly failing #include directive. Include file checking macros must be used as expressions in #if or #elif preprocessing directives.

See also: https://github.com/wenns/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

**Comment by jmecosta** [comment] 2015-07-03 15:16
My question is if they are all imported correctly. You can check that on
the analysis log

**Comment by KevinArturia** [comment] 2015-07-06 12:14
In the analysis log I can only see if there are some folder that does not exists, for instance:

    WARN  - the include root 'xxx' doesn't exist

But I can not see anything else related to the include.

**Comment by jmecosta** [comment] 2015-07-06 12:17
you need to run with -X, along the lines of

[08:27:50] :		 [Step 1/1] 08:27:50.552 DEBUG - Parse build log OK: includes: '238' defines: '238'
[08:27:50] :		 [Step 1/1] 08:27:50.605 DEBUG - storing include root: 'foldertoinclude'

**Comment by KevinArturia** [comment] 2015-07-06 12:26
I got the following result:

    DEBUG - Parse build log OK: includes: '1' defines: '1'

Then the list of all the path included is exactly the one I passed in my properties file

**Comment by jmecosta** [comment] 2015-07-06 13:53
So you say this only happens if you have more than 50 includes ?

**Comment by KevinArturia** [comment] 2015-07-06 13:59
yep

**Comment by guwirth** [comment] 2015-07-06 14:07
Did you check the **__has_include_next** point above.
This is a not supported clang keyword.

**Comment by KevinArturia** [comment] 2015-07-06 14:18
No I didn't because I do not get any error message when I have less than 50 includes.
Do you think this is just a coincidence?

**Comment by guwirth** [comment] 2015-07-06 14:25
Looking to the error message in your first comment ```Error evaluating expression '' for AstExp 'IDENTIFIER: __has_include_next', assuming 0"``` the ***__has_include_next*** is the root cause. Try to add a ```#define __has_include_next(s) 1``` to ```sonar.cxx.defines```. Other possibility is to write a small sample with ***__has_include_next***, same problem should occur. See http://clang.llvm.org/docs/LanguageExtensions.html.

**Comment by KevinArturia** [comment] 2015-07-06 14:33
I agree with you, but the thing is that I do not get any error message if I have less than 50 includes and it does not seem to matter which include I add/remove from my include list.

**Comment by jmecosta** [comment] 2015-07-07 10:41
actaully i also see some weird behaviour in my logs:

[08:03:39] :		 [Step 1/1] 08:03:39.832 INFO  - storing external macro: 'UNITTEST_VERSION -> '''

and then:
[09:15:44] :		 [Step 1/1] 09:15:44.447 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: UNITTEST_VERSION', assuming 0


wonder if it has to do with this extra ' when storing the macro

'_MSC_FULL_VER -> '180031101''

**Comment by jmecosta** [comment] 2015-07-07 10:43
usually this should not be a issue... as they are correctly passed to the build
/D UNITTEST_VERSION /D UNOFFICIAL_BUILD

**Comment by jmecosta** [comment] 2015-07-07 10:46
and it seems this is comming from the sslr core (com.sonar.sslr.api.RecognitionException )

    AstNode constExprAst = null;
    try {
      constExprAst = parser.parse(constExpr);
    } catch (com.sonar.sslr.api.RecognitionException re) {
      if (exprAst != null) {
        LOG.warn("Error evaluating expression '{}' for AstExp '{}', assuming 0", constExpr, exprAst.getToken());
      } else {
        LOG.warn("Error evaluating expression '{}', assuming 0", constExpr);
      }
      
      return BigInteger.ZERO;
    }

its worth to show the exception details likely

**Comment by jmecosta** [comment] 2015-07-07 11:06
this is the stacktrace EOF? @guwirth  this this means anything to you?

[14:00:15][Step 1/1] 14:00:11.716 WARN - Error evaluating expression '' for AstExp 'IDENTIFIER: UNITTEST_VERSION', assuming 0
[14:00:15][Step 1/1] 14:00:11.717 WARN - Exception: 'Parse error at line 1 column 0:
[14:00:15][Step 1/1] 
[14:00:15][Step 1/1]  --> EOF
[14:00:15][Step 1/1] ' -> '[org.sonar.sslr.internal.vm.Machine.parse(Machine.java:74), com.sonar.sslr.impl.Parser.parse(Parser.java:87), com.sonar.sslr.impl.Parser.parse(Parser.java:81), org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:58), org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:97), org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:79), org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:110), org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81), org.sonar.cxx.preprocessor.ExpressionEvaluator.eval(ExpressionEvaluator.java:52), org.sonar.cxx.preprocessor.CxxPreprocessor.handleIfLine(CxxPreprocessor.java:412), org.sonar.cxx.preprocessor.CxxPreprocessor.process(CxxPreprocessor.java:299), com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:159), com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:149), com.sonar.sslr.impl.Lexer.lex(Lexer.java:138), com.sonar.sslr.impl.Lexer.lex(Lexer.java:116), org.sonar.cxx.preprocessor.CxxPreprocessor.handleIncludeLine(CxxPreprocessor.java:517), org.sonar.cxx.preprocessor.CxxPreprocessor.process(CxxPreprocessor.java:311), com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:159), com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:149), com.sonar.sslr.impl.Lexer.lex(Lexer.java:138), com.sonar.sslr.impl.Lexer.lex(Lexer.java:97), com.sonar.sslr.impl.Lexer.lex(Lexer.java:83), com.sonar.sslr.impl.Parser.parse(Parser.java:68), org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:92), org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:124), org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:59), org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:51), org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:120), org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264), org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92), org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77), org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235), org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230), org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220), org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92), org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77), org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57), org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45), org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135), org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92), org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77), org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158), org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95), org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67), org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:45), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), java.lang.reflect.Method.invoke(Unknown Source), org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87), org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75), java.security.AccessController.doPrivileged(Native Method), org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69), org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50), org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102), org.sonar.runner.api.Runner.execute(Runner.java:90), org.sonar.runner.Main.executeTask(Main.java:70), org.sonar.runner.Main.execute(Main.java:59), org.sonar.runner.Main.main(Main.java:41)]'

**Comment by KevinArturia** [comment] 2015-07-22 11:49
I found a similar issue with a simple example.

I have a main.cpp which only includes <iostream> and get the following message in the log:
    
	13:25:35.254 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.256 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.258 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.258 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.259 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.260 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.261 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.262 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.263 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.264 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.264 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.265 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.266 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.267 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.267 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.268 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.269 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.270 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.270 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.271 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.272 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.273 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.273 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.277 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.278 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.279 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:35.281 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: __has_feature', assuming 0
	13:25:36.364 WARN  - Unable to find resource '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream' to create a dependency with 'test/test.cpp'


After running with `-X` I see that these come from:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config` and indeed this file is checking lots of c++ feature (cxx_exceptions, cxx_rtti, cxx_strong_enums ...).

Setting __has_feature to 0 in the `sonar.cxx.defines` removes the warnings but gives new errors

	13:45:30.773 DEBUG - [/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:37]: processing #include <__config>, resolved to file '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config'
	13:45:30.819 ERROR - Unable to parse file: /Volumes/SHARED/workspaces/dsp/test/test.cpp
	13:45:30.819 ERROR - Lexer error: Unable to lex url: file:/Volumes/SHARED/workspaces/dsp/test/test.cpp
	13:45:30.819 DEBUG - finished preprocessing '/Volumes/SHARED/workspaces/dsp/test/test.cpp'
	13:45:30.822 DEBUG - Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
	13:45:30.831 WARN  - Unable to find resource '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream' to create a dependency with 'test/test.cpp'

I don't think this is a solution anyway since we could lead to a different analysis path than the one compiler is using because obviously several feature are available.

I think this issue is related to the original one since it is about clang language extensions but maybe we 
could create another separate issue.

**Comment by guwirth** [comment] 2015-10-10 16:18
I'm closing this issue. Please re-open if still a problem.

**Closed by guwirth** 2015-10-10 16:18 UTC
Labels: question
